workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.41.2
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
