platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Parse .flutter-plugins to auto-discover pods
  plugins_file = File.join(File.dirname(File.realpath(__FILE__)), '..', '.flutter-plugins')
  if File.exist?(plugins_file)
    File.read(plugins_file).each_line do |line|
      next if line.strip.empty? || line.start_with?('#')
      name, path = line.split('=')
      next unless name && path
      pod name.strip, path: File.join(path.strip, 'ios')
    end
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
