platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = ENV['FLUTTER_ROOT']
if flutter_root && !flutter_root.empty?
  podhelper = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  require podhelper if File.exist?(podhelper)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
